sudo: required
services:
    - docker

script:
    - docker build -t $GIT_USER/node2 .
    - docker images $GIT_USER/node2

before_deploy:
    - docker login -u $GIT_USER -p $GIT_PASSWORD

deploy:
    provider: script
    script: docker push $GIT_USER/node2-test
    on:
        branch: master